### PR TITLE
Updates to run script as a service

### PR DESCRIPTION
**Pull request by bryanwulf**
Currently, the template.yaml file is only used to configure the service when deployed locally via AWS SAM CLI.

### CODE REVIEW

**Review by kilodalton — CHANGES_REQUESTED** [review]
The `VCI2cgsepio.py` does not have the proper code changes included, specifically regarding the affiliations file as used in production, or the the service using 3.9 in non-prod.

As used here:
`affiliation_file = os.path.join(os.path.dirname(__file__),"Affiliation_id_name_lookup.js")`

What is used by the production service:
`affiliation_file = os.path.join(os.path.dirname(__file__),"affiliations.json")`


You will also have to commit that affiliations file to the repo.

**Comment by bryanwulf** [comment]
@kilodalton The change from `Affiliation_id_name_lookup.js` to `affiliations.json` was cosmetic, so I chose not to keep it going forward (and use the file name from the base repo). All of the latest affiliation updates have been committed and pushed (to `Affiliation_id_name_lookup.js`).

Branch with current production code: `prod-20221114`

**Review by gcheung-SF — APPROVED** [review]
Codes look good.  I was able to set up local testing in virtual environment.  Tested both using python codes and running the service.  Tested with two snapshot files and compared results from local, non-prod and prod services, all have same result (other than the "contributionDate" of "publisher" role).

**Review by kilodalton — APPROVED** [review]

**Comment by kilodalton** [comment]
Production code currently exists on unprotected branch `prod-20221114`

**Pull request merged**
